### ISSUE TITLE
About the caffe weight files

### ISSUE THREAD

**Issue by Eric-BB** [aghagol/place-recognition#1]
Hello aghagol:

Thanks for sharing your code ,it's really helpful! Could you tell me where I can download the weight files? Thanks!

**Comment by aghagol** [comment]
Hi Eric. I think you can find the weights in model zoo: https://github.com/BVLC/caffe/wiki/Model-Zoo#places-cnn-model-from-mit download link for weights is http://places.csail.mit.edu/model/placesCNN.tar.gz . Thanks.

**Comment by Eric-BB** [comment]
Thanks a lot!

**Comment by Eric-BB** [comment]
Thanks a lot! I have solve the problem.
