### ISSUE TITLE
Gardens Point dataset.

### ISSUE THREAD

**Issue by Eric-BB** [aghagol/place-recognition#2]
Hi,aghagol! Could you tell me where I can download the Gardens Point dataset? The previous link has failed.

Thanks.

**Comment by aghagol** [comment]
Strange, the link works for me. I uploaded the images in the PR_bench folder.

**Comment by Eric-BB** [comment]
Oh,  thanks!

**Comment by mrgransky** [comment]
It seems to be locked now and accessible only to users of QUT!

![Screenshot from 2020-03-06 13-43-48](https://user-images.githubusercontent.com/11946010/76080899-a37d4480-5fb0-11ea-8af1-46aff5651051.png)

**Comment by MareSorin-Alexandru** [comment]
The resource is not locked, just moved somewhere else in the site.
Here is the updated location of the dataset. @mrgransky 

https://wiki.qut.edu.au/display/raq/Day+and+Night+with+Lateral+Pose+Change+Datasets

**Comment by aghagol** [comment]
Thanks @Skcoica, updated the link in README.

**Comment by mrgransky** [comment]
@Skcoica There is this error still with ur link:
![gp_error](https://user-images.githubusercontent.com/11946010/122941903-78259100-d37e-11eb-940c-dcba5dd70231.png)

**Comment by MareSorin-Alexandru** [comment]
@mrgransky they must have moved the resource somewhere else on the site (again). Haven't used it since.

**Comment by owlshrimp** [comment]
README link is dead again. In fact, the whole wiki subdomain seems unresponsive.

**Comment by LiKangyuLKY** [comment]
If someone finds the new link, please leave a comment. Thanks!

**Comment by Tobias-Fischer** [comment]
Here is the download link: https://mega.co.nz/#!XAZHgZYa!Rp83z96sc5iiSeV2LC1INyNTYt3JM2utQ8_9yms3Fg8 ("The Gardens Point Walking dataset consists of three folders each with 200 images each. The image name indicates correspondence in location between each of the three route traversals.")

For the South Bank Bicycle dataset (The South Bank Bicycle dataset consists of 2 folders each with 400 images each. Image names indicate positional correspondance between traversals.): https://mega.co.nz/#!3FJ1DDTB!yu4SloQSCpMYDfJepjCmv4U6RcUIXnwYRH7Kmr9RmBM

**Comment by mrgransky** [comment]
@Tobias-Fischer I was wondering which paper I should reference The Gardens Point Walking dataset if I am using it in my research paper. Is it this paper:
[On the Performance of ConvNet Features for Place Recognition](https://ieeexplore.ieee.org/document/7353986)

**Comment by Tobias-Fischer** [comment]
Yes, I think this is correct.

**Comment by oravus** [comment]
Hi all, [here's](https://zenodo.org/record/4590133#.YjFMeoRBzJk) the public link to the original source of Gardens Point and related datasets, contributed by Arren Glover (as also acknowledged in [On the Performance of ConvNet Features for Place Recognition](https://ieeexplore.ieee.org/document/7353986)). 

If you only want to cite the standalone dataset, you can use the citation provided on Zenodo.

[Here's](https://github.com/MubarizZaffar/VPR-Bench) a list of some established VPR datasets for which correct citations have already been carefully looked into.
